### ISSUE TITLE
Modificaciones del archivo css

### ISSUE THREAD

**Issue by yaninagm** [yesdoc/web#10]
Añadir fucncionalidades que Bootstrap 3.3.4 no tien.

**Comment by adamantike** [comment]
Qué tipo de funcionalidades?

**Comment by yaninagm** [comment]
Van a ir saliendo con el tiempo, espero que no sean muchas. En el pull request añadi la de <<callout>> que se uso en Bootstrap 3.2 y no esta en la 3.3.4
