### ISSUE TITLE
Medium - Grupo - Opción de tipo de membresia incorrecto

### ISSUE THREAD

**Issue by caballerojavier13** [yesdoc/web#104]
![image](https://cloud.githubusercontent.com/assets/2935783/11024796/84f879ec-8672-11e5-9162-04666c53cc25.png)

La opción <"hijo> aparece con comillas en el campo tipo de membresia.

**Comment by adamantike** [comment]
Corregido desde la base de datos! Listo para probar @caballerojavier13

**Comment by caballerojavier13** [comment]
![image](https://cloud.githubusercontent.com/assets/2935783/11118864/10fbe72c-8924-11e5-8fe7-9d2640eaac45.png)
