### ISSUE TITLE
Medium - Análisis - Cargar Medición - Error en el guardado

### ISSUE THREAD

**Issue by caballerojavier13** [yesdoc/web#109]
![image](https://cloud.githubusercontent.com/assets/2935783/11025068/795407b6-8675-11e5-83de-dd27995b18f6.png)

Cuando se guardad correctamente sería deseable que el sistema o cerrara el modal de carga o que vacíe los campos para poder seguir registrando mediciones.

Comentario visual:  El mensaje tiene un color que es molesto cuando se trabaja de noche. Se recomienda cambiarlo por el mismo color verde de la barra de menú de la derecha, o un tono mucho más oscuro.

**Comment by adamantike** [comment]
Aún no está resuelto.

**Comment by yaninagm** [comment]
@adamantike y ahora??

**Comment by navicor90** [comment]
@caballerojavier13 Revisa este Issue
