### ISSUE TITLE
Low - Resumen - No se aprovecha el ancho de pantalla

### ISSUE THREAD

**Issue by caballerojavier13** [yesdoc/web#113]
![Uploading image.png…]()

El sistema no aprovecha todo el ancho de pantalla para listar las mediciones en la funcionalidad de Resumen. Cabe indicar que el resto de las funcionalidades aprovechan bien el tamaño.

**Comment by yaninagm** [comment]
@caballerojavier13  si agrandamos la ficha los datos van a quedar muy distante, si querés te propongo añadir algo a la derecha para ocupar ese espacio.

@adamantike porque es importante para la expo?

**Comment by caballerojavier13** [comment]
![image](https://cloud.githubusercontent.com/assets/2935783/11119187/7ebf4522-8926-11e5-9897-486fbbec82ab.png)


@yaninagm , @adamantike Propongo una solución fácil. Centrar el listado.

**Comment by adamantike** [comment]
Corregido en #140.
