### ISSUE TITLE
La edición de la medición  no permite seleccionar un valor

### ISSUE THREAD

**Issue by yaninagm** [yesdoc/web#130]
En la seccion de carga de análisis, una vez cargada la medición, al editar la misma, esta no permite seleccionar un valor.
Solo permite seleccionar un valor si se "limpia" todo el contenido, seleccionando otro tipo de medición.
![edicion_medicion](https://cloud.githubusercontent.com/assets/3909570/11119774/a1bfde7a-892a-11e5-8b87-cf1464bc2595.png)

**Comment by adamantike** [comment]
Corregido en #136.
