### ISSUE TITLE
Al actualizar la página web pierdo el Token

### ISSUE THREAD

**Issue by yaninagm** [yesdoc/web#48]
Yo presumo que al actualizar con F5 la página pierdo las cookies y por lo tanto el token.

**Comment by yaninagm** [comment]
(Probar con un alert, mostrar el token para ver que es lo que tiene y si es que en verdad se está perdiendo el valor.)

**Comment by adamantike** [comment]
Puede que este artículo sirva para solucionarlo: [Maintaining session info in AngularJS when you refresh the page](http://maffrigby.com/maintaining-session-info-in-angularjs-when-you-refresh-the-page/).
