### ISSUE TITLE
Presentación Web

### ISSUE THREAD

**Issue by yaninagm** [yesdoc/web#6]
## Armar la presentación del esqueleto de la página
* Cambiar el logo, principalmente los colores.
* Modificar los contenedores de las presentaciones.
* Mostrar la seleccion de los navs.

**Comment by yaninagm** [comment]
¿Donde ubicar el código que se urilizará a lo largo de la aplicación? En muchos lugares recomiendan utilizar service.
Pero en el caso del manejo de nav recomiendan en controllers
https://github.com/yeoman/generator-angular/issues/895
http://magmax.org/blog/2014/1/18/primeros-pasos-en-angularjs/

**Comment by navicor90** [comment]
Este issue, ya no lo desarrollaste?

**Comment by fede9123** [comment]
yo creo que @yaninagm  tiene razón....
